### ISSUE TITLE
Tilemap: Nível 1

### ISSUE THREAD

**Issue by pedrykolas** [El-Gato-Gordo/MageKnight#11]

**Comment by CaioBongs** [comment]
[sprite grama.zip](https://github.com/El-Gato-Gordo/Jogo/files/8554023/sprite.grama.zip)

**Comment by CaioBongs** [comment]
[360_F_219368358_8Mdf8ekeNZiyf9UTN3qtehvDTRauQw1P.zip](https://github.com/El-Gato-Gordo/Jogo/files/8562965/360_F_219368358_8Mdf8ekeNZiyf9UTN3qtehvDTRauQw1P.zip)

**Comment by CaioBongs** [comment]
![New Piskel](https://user-images.githubusercontent.com/102802026/165941797-e3fb7ea4-ae82-4e90-ab6a-4920286a41d5.png)

**Comment by CaioBongs** [comment]
![165959286-bbdc6ef0-cb72-451d-9b90-c297ea7a77c5 (1)](https://user-images.githubusercontent.com/102802026/166231658-501ff40a-191f-447f-b8f3-1da2465c1cfe.png)

**Comment by CaioBongs** [comment]
![aaaaa (1)](https://user-images.githubusercontent.com/102802026/166913170-4af6a57a-a916-4009-a3d0-aae405ef8943.png)

**Comment by alanos005** [comment]
![fundo1](https://user-images.githubusercontent.com/102801485/167406169-f36c2f4c-b1d6-4f10-abf5-c40fccc2870d.png)

**Comment by CaioBongs** [comment]
chão 128 x 72

**Comment by CaioBongs** [comment]
![2d-pixel-art-retro-game-600w-1352418344](https://user-images.githubusercontent.com/102802026/168068066-a8fb1c12-e51f-4e02-98cc-a24bec1bf6bc.png)

**Comment by CaioBongs** [comment]
![New Piskel](https://user-images.githubusercontent.com/102802026/170484335-9cfd4b62-6e31-4f7e-820f-805fa40efaaa.png)

**Comment by CaioBongs** [comment]
![image](https://user-images.githubusercontent.com/102802026/175554463-63115655-5d22-43d3-929c-03332f958161.png)

**Comment by CaioBongs** [comment]
![image](https://user-images.githubusercontent.com/102802026/176667837-7ba6a9c3-a7d5-4052-aa12-ba41b8e41400.png)

**Comment by CaioBongs** [comment]
![image (2)](https://user-images.githubusercontent.com/102802026/176675585-55af81c8-7bb8-4316-8ad4-113e4eecaab6.png)

**Comment by CaioBongs** [comment]
![image](https://user-images.githubusercontent.com/102802026/176987228-a40c2654-5742-4fba-982d-d3aea3830b61.png)
NAO AHUENO MAIS FAZE PONTIHNO

**Comment by CaioBongs** [comment]
![image](https://user-images.githubusercontent.com/102802026/177325909-17d5c423-853e-4c90-9448-a84d2d81939d.png)
aa

**Comment by CaioBongs** [comment]
![image](https://user-images.githubusercontent.com/102802026/177770748-be3c7905-eb25-45f1-bf11-4d5d19ef6948.png)
sherk

**Comment by CaioBongs** [comment]
![image (1)](https://user-images.githubusercontent.com/102802026/178126630-9ab70dd4-d29e-4ad6-bbd0-95e693e4ca88.png)

**Comment by CaioBongs** [comment]
![image (2)](https://user-images.githubusercontent.com/102802026/178161090-cd83dea4-cc7f-4a8e-871d-03d4685e8835.png)

**Comment by CaioBongs** [comment]
![image](https://user-images.githubusercontent.com/102802026/178250076-1c632e06-2449-46d3-9ba0-8c1efc7952f6.png)

**Comment by CaioBongs** [comment]
![New Piskel](https://user-images.githubusercontent.com/102802026/178255474-05df5e61-8f2e-47d4-8f63-9e9a7e8c3fe8.png)
AND IT WILL FLOOD

**Comment by alanos005** [comment]
![sei la oq eh isso](https://user-images.githubusercontent.com/102801485/179373216-7c21b554-9b3d-400c-8276-6a0b0175313f.png)

**Comment by CaioBongs** [comment]
tenho que aprender a usar paletas huh
