### ISSUE TITLE
Cenas / Roteiro

### ISSUE THREAD

**Issue by alanos005** [El-Gato-Gordo/MageKnight#13]
Cena Inicial: 
Quando o jogo se inicia, a tela de transição vem do completo escuro até ter a imagem completa. A primeira cena que aparece é o cenário, logo após o mago aparece correndo e a câmera se centra nele. Atrás dele, o cavaleiro sombrio o persegue. Ao continuarem a perseguição, o mago se encontra encurralado (nesse momento a câmera se encontra no centro, e o mago no canto, onde a grande árvore obstrui seu caminho). O cavaleiro prepara por um momento sua magia (bola de fogo verde) e dispara em direção ao mago. Nesse momento do arbusto de trás pula o cavaleiro principal (na frente do mago), desintegrando o ataque do inimigo, numa tentativa de defender o mago (quando isso acontece, a armadura sofre um knock-back, enquanto se mantém na "pose de deflexão", imóvel). Após o momento,  o Sombrio faz um movimento como se tivesse puxando algo, e depois de um momento, uma esfera de energia (energia vital) (que diminui e aumenta de luminosidade, periodicamente) que sai lentamente da armadura. Após se apoderar da energia vital do cavaleiro, e segura-la em sua mão, o Sombrio desaparece. Após isso a armadura do cavaleiro cai inteira do chão e então o mago se aproxima. Após canalizar por um tempo, o pequeno mago lança um feitiço na armadura, dando vida a ela, ao mesmo tempo que runas e efeitos em azul tomam conta dela. Ao terminar o feitiço, os olhos da armadura piscam em azul. 

Cena final:
Após a barra do boss zerar. O HUD some e ele se ajoelha. O cavaleiro vai andando para perto do inimigo, e quando chega perto, ele o finaliza. Após isso o cavaleiro junto ao mago andam até a grande porta no final do mapa e passam por ela. Quando isso acontece a tela escurece e escrito no meio: O cavaleiro e o mago irão retornar.

**Comment by CaioBongs** [comment]
Scrapped
