### ISSUE TITLE
Spritesheets de Menu

### ISSUE THREAD

**Issue by pedrykolas** [El-Gato-Gordo/MageKnight#34]
![image (2)](https://user-images.githubusercontent.com/104366549/174684361-657d7c1c-f223-4e87-a749-f0ff52d05f3e.png)

![image (1)](https://user-images.githubusercontent.com/75922056/176777390-679b4cab-3642-4e8a-895c-641e896ac027.png)

**Comment by CaioBongs** [comment]
![gato](https://user-images.githubusercontent.com/102802026/165098223-32733c35-3ade-4dd2-99ea-4e032317c32c.jpeg)
