### ISSUE TITLE
NOME DO JOGO!

### ISSUE THREAD

**Issue by pedrykolasAlt** [El-Gato-Gordo/MageKnight#35]
Nome do Jogo: _**MageKnight**_

Logo: 
![LOGO](https://user-images.githubusercontent.com/75922056/166125325-f5618a30-4239-4d64-a5d8-a888eb0347e5.png)

 Spritesheet da Logo:
![image](https://user-images.githubusercontent.com/75922056/166127005-c1e5a598-444d-42fe-9be9-51be2771d9c1.png)

El Gato Gordo

![image](https://user-images.githubusercontent.com/75922056/168697899-95615c7a-169c-49d6-a490-3ef700b758a7.png)

**Comment by pedrykolasAlt** [comment]
LOGO: (to fazendo ainda)
![image](https://user-images.githubusercontent.com/104366549/165187804-4737b69f-b4e3-4e3c-9c62-25983f161883.png)

**Comment by pedrykolasAlt** [comment]
![image](https://user-images.githubusercontent.com/104366549/165296735-07541349-f169-482b-bdf8-97e677d97b06.png)

**Comment by CaioBongs** [comment]
nonotiao!
