### ISSUE TITLE
Criar Sprites Personalizados

### ISSUE THREAD

**Issue by pedrykolas** [El-Gato-Gordo/MageKnight#36]
_**MOVIMENTAÇÃO BASE:**_

**IDLE:**
Tamanho de cada Frame: 150x150 [Feito em 75x75]

[Resultado]
![image (4)](https://user-images.githubusercontent.com/104366549/172948922-37a27651-287a-4f44-a329-959a63dba724.gif)

[Aumentado]
![image (2) (1)](https://user-images.githubusercontent.com/104366549/172951260-203b26da-430d-4234-bcad-95acc900b1da.png)

![image (2) (3)](https://user-images.githubusercontent.com/104366549/172951317-c76bcfb4-d647-47cd-8653-8adf798274c0.png)

[Original]
![image (2)](https://user-images.githubusercontent.com/104366549/172951250-857fcc2d-5020-4a76-a087-3b1ded136d3f.png)

![image (2) (2)](https://user-images.githubusercontent.com/104366549/172951293-ba3fb404-9620-410a-b9d7-e45e62de463f.png)

**WALK:**
Tamanho de cada Frame: 150x150 [Feito em 75x75]

[Resultado]
![image](https://user-images.githubusercontent.com/104366549/172955259-e546deaf-c589-4257-a674-edaee6b0cdfa.gif)

[Aumentado]
![image (7)](https://user-images.githubusercontent.com/104366549/172910745-397683da-c773-4cb9-b811-36cc282cab7c.png)

![image (9)](https://user-images.githubusercontent.com/104366549/172910802-7c72951b-2c0a-4057-a7e1-612fe80458ce.png)

[Original]
![image (6)](https://user-images.githubusercontent.com/104366549/172910751-d6d22b72-9f63-4094-8269-0528a36eeb77.png)

![image (8)](https://user-images.githubusercontent.com/104366549/172910796-0a5fc7a9-fecb-4c37-b3a4-33fb88dc3562.png)

**RUN:**

![image](https://user-images.githubusercontent.com/75922056/176661618-692416b0-7722-438f-81db-7a67694acc55.png)
![image (1)](https://user-images.githubusercontent.com/75922056/176661631-4c917930-fb59-4a59-9616-1787fe169cb6.png)

**RISING AND FALLING:**
Tamanho de cada Frame: 150x150 [Feito em 75x75]

[Resultado]
![image](https://user-images.githubusercontent.com/104366549/172957944-120b779c-203b-4c27-8676-79af35fe5637.gif)

[Aumentado]
![bigRiseRight](https://user-images.githubusercontent.com/104366549/172956920-100e1ca5-cda3-4d01-96b6-14052437f6bd.png)

![bigRiseLeft](https://user-images.githubusercontent.com/104366549/172956919-5fe4d795-804a-4c6f-86d5-03d72649e44e.png)

![bigFallRight](https://user-images.githubusercontent.com/104366549/172956991-c01ecdc0-9925-4d8f-a663-10328127d8e8.png)

![bigFallLeft](https://user-images.githubusercontent.com/104366549/172956996-2f801810-7f43-4824-819b-180f53db2af6.png)

[Original]
![smallRiseRight](https://user-images.githubusercontent.com/104366549/172956962-76f4206b-8d5e-44d8-8d70-0062b3559d7e.png)

![smallRiseLeft](https://user-images.githubusercontent.com/104366549/172956967-c6041bdb-3c6a-48d0-90df-1908da984f8c.png)

![smallFallRight](https://user-images.githubusercontent.com/104366549/172957014-5529d6ac-42b8-4542-86f7-9ebf7a63a7cf.png)

![smallFallLeft](https://user-images.githubusercontent.com/104366549/172957023-1290c6ad-8ca7-40ac-8555-8af7b27ae892.png)

**ATTACKING**
![image (1)](https://user-images.githubusercontent.com/75922056/178167273-fa6f7c1b-8380-4a16-9d87-0891b7175f15.png)

![image](https://user-images.githubusercontent.com/75922056/178167271-e2e0fbaa-ac8c-41f3-a9f8-b0f53b3d7555.png)

**Comment by alanos005** [comment]
![sprite1_knight](https://user-images.githubusercontent.com/102801485/168272678-d33a0974-01a6-4c2e-a27c-650b3ad6cc3c.png)

**Comment by pedrykolasAlt** [comment]
![image](https://user-images.githubusercontent.com/104366549/168293202-28eb980a-8a57-4b44-b20a-0d5a264099ad.png)

**Comment by alanos005** [comment]
![sprite1_knightready1](https://user-images.githubusercontent.com/102801485/172266235-7d09ab75-df9e-4221-b942-5dd333fe8015.png)

**Comment by alanos005** [comment]
![sprite1_knightready1](https://user-images.githubusercontent.com/102801485/172266377-299b4ca9-698e-4cfb-b832-06f908124a58.png)

**Comment by pedrykolasAlt** [comment]
Espadão:
![image](https://user-images.githubusercontent.com/104366549/172441357-ab8b0180-57ad-4bf6-8ada-cb89b6924a6e.png)

**Comment by pedrykolasAlt** [comment]
teste: ![image](https://user-images.githubusercontent.com/104366549/172940353-b7c8a133-5656-4572-a6a4-fde9eb591e58.png)

**Comment by alanos005** [comment]
![corrida_cavaleiro1](https://user-images.githubusercontent.com/102801485/175788351-fb02534f-d739-4cd1-a36e-238d260ab224.png)

**Comment by alanos005** [comment]
![caminhada_cavaleiro1](https://user-images.githubusercontent.com/102801485/175788797-bb925bab-a68d-4820-b808-7831fca210ec.png)

animação do walk melhorada

**Comment by pedrykolas** [comment]
ataques loco de teste pq o alan demora mt pra fazer os sprite

@alanos005 @alanos005 @alanos005 

![MK-sideatkRight](https://user-images.githubusercontent.com/75922056/177221190-27917d4a-8229-4a37-adfd-a3760e07d161.png)
![MK-sideatkLeft](https://user-images.githubusercontent.com/75922056/177221185-ef098c58-cadb-4e43-9c77-533596b8b8c7.png)

**Comment by alanos005** [comment]
![ataque_aéreo_cavaleiro](https://user-images.githubusercontent.com/102801485/179364996-30361092-8b16-43af-ace4-8ef53a1f9402.png)

**Comment by alanos005** [comment]
![maozinha](https://user-images.githubusercontent.com/102801485/179365951-a18354e5-3d56-48ce-bff3-81934a11212d.png)
maozinha

**Comment by alanos005** [comment]
![projprov1](https://user-images.githubusercontent.com/102801485/179367113-88254564-20d7-4491-86cd-43ca8180396a.png)
![projprov2](https://user-images.githubusercontent.com/102801485/179367114-686bfd27-7ce6-45c2-8299-f551f715d842.png)

**Comment by alanos005** [comment]
![projprov1](https://user-images.githubusercontent.com/102801485/179367133-147bec13-ed04-4b86-8799-aa487bf9e623.png)
![projprov2](https://user-images.githubusercontent.com/102801485/179367134-16792fb6-0106-43f7-8412-4b803c7c2362.png)

**Comment by alanos005** [comment]
![concept1_bossx](https://user-images.githubusercontent.com/102801485/179431105-68cc3d8f-afea-4e79-b762-8bb9dcaa34df.png)

**Comment by alanos005** [comment]
![shield1](https://user-images.githubusercontent.com/102801485/179431154-6aee5da9-c10e-4bd9-a48a-a8d81252e427.png)
parry do mago

**Comment by alanos005** [comment]
![CONCEPT1CONTINUAÇÃO_AREVOLTA1](https://user-images.githubusercontent.com/102801485/179431418-64134434-1860-4790-9773-47719b4ccc96.png)

**Comment by alanos005** [comment]
![Uploading CONCEPT1CONTINUAÇÃO_AREVOLTA1.png…]()

**Comment by alanos005** [comment]
![CONCEPT1CONTINUAÇÃO_AREVOLTA1](https://user-images.githubusercontent.com/102801485/179431476-6bd76c21-ffec-4691-b2b9-cd6af187eaa5.png)

**Comment by pedrykolas** [comment]
![image](https://user-images.githubusercontent.com/75922056/180217302-b0156ed1-737f-4c38-8fa6-5331d3316f37.png)

**Comment by CaioBongs** [comment]
![image](https://user-images.githubusercontent.com/102802026/180299823-45fafb5b-f417-4771-a659-4ea6920a0a3e.png)

**Comment by alanos005** [comment]
![logo512](https://user-images.githubusercontent.com/102801485/180300042-6330e801-9764-4556-8887-a4dcebc3dc8c.png)
![logo384](https://user-images.githubusercontent.com/102801485/180300046-6c48be30-3ff4-472d-a483-7fd98e316ba6.png)
![logo256](https://user-images.githubusercontent.com/102801485/180300048-56654b9b-abfa-4b67-b749-ea22c7dec3ac.png)
![logo192](https://user-images.githubusercontent.com/102801485/180300049-f278d098-32a3-43ab-b4bd-e12f163ef2de.png)
![logo128](https://user-images.githubusercontent.com/102801485/180300051-67f499bc-1093-48e2-bbf8-0453f94fe5b8.png)

**Comment by CaioBongs** [comment]
![BOSS_WAKENING_SPRITE1](https://user-images.githubusercontent.com/102801485/179629198-f2f19a61-294f-4ff2-9183-f9b70e25e2ef.png)
![BOSS_WAKENING_SPRITE2](https://user-images.githubusercontent.com/102801485/179629200-16ad1d22-73b4-42bf-aa47-e8bf49d4f8b5.png)
![BOSS_WAKENING_SPRITE3](https://user-images.githubusercontent.com/102801485/179629201-911507a5-32a3-4ebb-9c08-0b4fbb25f6bd.png)
![BOSS_WAKENING_SPRITE4](https://user-images.githubusercontent.com/102801485/179629204-a95c02e4-99c0-406d-beea-66fd3c8ef9de.png)
![BOSS_WAKENING_SPRITE5](https://user-images.githubusercontent.com/102801485/179629205-e1f47217-0011-42b2-a915-7a6123dba4d7.png)
![BOSS_WAKENING_SPRITE6](https://user-images.githubusercontent.com/102801485/179629207-8425f557-13b5-4114-b28d-2edbf00dd7fa.png)
![BOSS_WAKENING_SPRITE7](https://user-images.githubusercontent.com/102801485/179629208-932f5bee-bd0d-4482-be46-a80bf64541d1.png)
![BOSS_WAKENING_SPRITE8](https://user-images.githubusercontent.com/102801485/179629209-c3f2fc22-1448-4b0f-8e48-c88ad482e00c.png)
![BOSS_WAKENING_SPRITE9](https://user-images.githubusercontent.com/102801485/179629211-8df3f1f5-ac00-4ade-93e2-0a5a057694d5.png)
![BOSS_WAKENING_SPRITE10](https://user-images.githubusercontent.com/102801485/179629212-329be18a-d90c-41c3-a701-afb4ba959b58.png)
![BOSS_WAKENING_SPRITE11](https://user-images.githubusercontent.com/102801485/179629214-75fe7df9-965b-4536-90e9-79ce2bf2644d.png)
![BOSS_WAKENING_SPRITE12](https://user-images.githubusercontent.com/102801485/179629215-3118c7b7-b002-4346-921a-07706b7a60e1.png)
![BOSS_WAKENING_SPRITE13](https://user-images.githubusercontent.com/102801485/179629219-9b379dd9-9820-42ae-ba5c-d117a68b08f6.png)
![BOSS_WAKENING_SPRITE14](https://user-images.githubusercontent.com/102801485/179629223-1fc006db-688b-420b-bb94-06b6c16aba32.png)
![BOSS_WAKENING_SPRITE15](https://user-images.githubusercontent.com/102801485/179629224-f9ffcabe-6d47-4880-ad44-326ea208e9a8.png)
![BOSS_WAKENING_SPRITE16](https://user-images.githubusercontent.com/102801485/179629226-64b46356-345b-412f-ba76-75c3b29dede3.png)
![BOSS_WAKENING_SPRITE17](https://user-images.githubusercontent.com/102801485/179629228-9874a851-cdb6-4f54-a1a7-219ca710438c.png)
![BOSS_WAKENING_SPRITE18](https://user-images.githubusercontent.com/102801485/179629231-4e259037-738e-4a38-b782-1682c3e86533.png)
![BOSS_WAKENING_SPRITE19](https://user-images.githubusercontent.com/102801485/179629232-3949f163-d8be-4b0a-8a77-2135beb7771a.png)
![BOSS_WAKENING_SPRITE20](https://user-images.githubusercontent.com/102801485/179629235-35bc34fb-92bd-4419-8fb2-7d61f835f04d.png)

Animação Inicial (FASE1) - AWAKENING

**Comment by CaioBongs** [comment]
![BOSS_ATTACKING_FASE1](https://user-images.githubusercontent.com/102801485/179630037-99e5cc90-02b4-4d3a-b2b5-789237d54697.png)
![BOSS_ATTACKING_FASE2](https://user-images.githubusercontent.com/102801485/179630041-d3fc0a47-e64f-43e0-9f0f-9b5c4ff78883.png)
![BOSS_ATTACKING_FASE3](https://user-images.githubusercontent.com/102801485/179630044-b1b6ccb0-9ef9-4329-a9b3-29159a6f89ab.png)
![BOSS_ATTACKING_FASE4](https://user-images.githubusercontent.com/102801485/179630045-5c077880-be94-4961-ac37-256a1aab8cbd.png)
![BOSS_ATTACKING_FASE5](https://user-images.githubusercontent.com/102801485/179630046-6a8d694c-0181-47ba-809a-0d4b62639dea.png)
![BOSS_ATTACKING_FASE6](https://user-images.githubusercontent.com/102801485/179630048-3a274902-818d-446b-9ff1-67c1fa62fc42.png)
![BOSS_ATTACKING_FASE7](https://user-images.githubusercontent.com/102801485/179630049-689960e5-6c00-4c9d-88bf-c348ed5b23c5.png)
![BOSS_ATTACKING_FASE8](https://user-images.githubusercontent.com/102801485/179630050-a33776c7-b0aa-44c8-9aff-8075c1b8f49a.png)
![BOSS_ATTACKING_FASE9](https://user-images.githubusercontent.com/102801485/179630052-9871e074-300c-4dad-87ae-90a4e6ed8b05.png)
![BOSS_ATTACKING_FASE10](https://user-images.githubusercontent.com/102801485/179630054-4c2bbd9a-8d85-4992-8fae-7c2046534fc5.png)
![BOSS_ATTACKING_FASE11](https://user-images.githubusercontent.com/102801485/179630055-722e78b3-71c5-48f0-bbbc-2e2a4e3bb1cb.png)

Animação de Ataque (FASE 1)

**Comment by CaioBongs** [comment]
![BOSS_FASE2_CHARGING1](https://user-images.githubusercontent.com/102801485/179644800-1f7f6e5d-8281-4cf4-9765-5eb9ba693272.png)
![BOSS_FASE2_CHARGING2](https://user-images.githubusercontent.com/102801485/179644801-e0bee0df-effe-42d6-a4af-22ef99bdbe58.png)
![BOSS_FASE2_CHARGING3](https://user-images.githubusercontent.com/102801485/179644807-e73c38c8-71f5-45ae-80d4-26e414c225f2.png)
![BOSS_FASE2_CHARGING4](https://user-images.githubusercontent.com/102801485/179644811-920c7d66-4a31-4590-8d2d-a305a4cb8843.png)
![BOSS_FASE2_CHARGING5](https://user-images.githubusercontent.com/102801485/179644813-07feb004-02de-4bee-b21a-2cc8901f72ec.png)
![BOSS_FASE2_CHARGING6](https://user-images.githubusercontent.com/102801485/179644814-198a4547-3aab-4eda-9a93-c2dc3ce7a2f5.png)
![BOSS_FASE2_CHARGING7](https://user-images.githubusercontent.com/102801485/179644815-8348ed4c-1150-4c3f-8295-75f5be4c5596.png)
![BOSS_FASE2_CHARGING8](https://user-images.githubusercontent.com/102801485/179644817-6628474d-84b9-4ae8-b9be-4833bad21e12.png)
![BOSS_FASE2_CHARGING9](https://user-images.githubusercontent.com/102801485/179644818-a9b9a900-fc71-43ff-bd20-34b8e418ba97.png)
![BOSS_FASE2_CHARGING10](https://user-images.githubusercontent.com/102801485/179644821-3a1b8c61-44b6-4319-b31a-ff36b650152f.png)
![BOSS_FASE2_CHARGING11](https://user-images.githubusercontent.com/102801485/179644822-58e4a139-826f-46c5-b49a-fb54865ce031.png)
![BOSS_FASE2_CHARGING12](https://user-images.githubusercontent.com/102801485/179644823-12b7171c-d9b0-4d3c-b320-d0096f57ba1e.png)
![BOSS_FASE2_CHARGING13](https://user-images.githubusercontent.com/102801485/179644826-1b1bd13b-e7ed-4d5f-aa23-c119e0685a88.png)
![BOSS_FASE2_CHARGING14](https://user-images.githubusercontent.com/102801485/179644827-50cc38df-8bfe-4d19-a6d1-ad236aa772c7.png)
![BOSS_FASE2_CHARGING15](https://user-images.githubusercontent.com/102801485/179644829-70a58801-6839-484e-bc52-519bea9ee2b7.png)
![BOSS_FASE2_CHARGING16](https://user-images.githubusercontent.com/102801485/179644831-6e07dc38-7207-486e-8d3b-bb210a46e9ca.png)
![BOSS_FASE2_CHARGING17](https://user-images.githubusercontent.com/102801485/179644832-2d7b0282-7422-4613-bb6c-f35d0a45807f.png)
![BOSS_FASE2_CHARGING18](https://user-images.githubusercontent.com/102801485/179644833-2ccc507d-0a8a-4790-a37c-fe4d4c4da04e.png)
![BOSS_FASE2_CHARGING19](https://user-images.githubusercontent.com/102801485/179644836-04d5bc15-f584-4a5a-9e23-d945b7ca3faf.png)

Animação de Transição (FASE 1 > FASE 2)

**Comment by CaioBongs** [comment]
![MAGE_SPELL_1](https://user-images.githubusercontent.com/102801485/179769337-33fe70b9-9de6-48ea-bdd1-c78de41eadce.png)
![MAGE_SPELL_2](https://user-images.githubusercontent.com/102801485/179769343-5bcd151f-f7c9-4a11-85bd-caa3c95b4b83.png)
![MAGE_SPELL_3](https://user-images.githubusercontent.com/102801485/179769346-90262143-8049-4d42-ae8e-f70ca08ff938.png)
![MAGE_SPELL_4](https://user-images.githubusercontent.com/102801485/179769350-63953d0c-e572-438e-bf0f-aba95893e4a1.png)

Sprites de projétil do mago

**Comment by CaioBongs** [comment]
![spell_collide 1](https://user-images.githubusercontent.com/102801485/180030131-fd3f4aa7-0953-4985-bffe-f99dbad52119.png)
![spell_collide 2](https://user-images.githubusercontent.com/102801485/180030134-5f6cfcb0-9574-43b1-aa62-9d593aac42e5.png)
![spell_collide 3](https://user-images.githubusercontent.com/102801485/180030139-83eeb5ae-a242-4db8-8d2c-654c8fa604bc.png)
![spell_collide 4](https://user-images.githubusercontent.com/102801485/180030140-c4b141b5-4d49-4167-b8d2-8128ddb067e6.png)
![spell_collide 5](https://user-images.githubusercontent.com/102801485/180030142-096772e2-6db6-4d89-b697-bedbe44f43b0.png)

Sprites de colisão do projétil do mago

**Comment by alanos005** [comment]
![boss_spell_collide 1](https://user-images.githubusercontent.com/102801485/180312036-043478ad-781a-4078-bf1e-9d4815224188.png)
![boss_spell_collide 2](https://user-images.githubusercontent.com/102801485/180312040-c3a4155a-9fe1-4b90-b853-75f4f81159bc.png)
![boss_spell_collide 3](https://user-images.githubusercontent.com/102801485/180312041-fb09807b-e557-4c06-984c-951af949c4ec.png)
![boss_spell_collide 4](https://user-images.githubusercontent.com/102801485/180312043-d0dede2e-d829-42ab-ac7f-9cd845bc8861.png)
![boss_spell_collide 5](https://user-images.githubusercontent.com/102801485/180312046-32693849-3b89-4546-a446-9422a0132960.png)
![boss_spell_collide 6](https://user-images.githubusercontent.com/102801485/180312050-063c309a-2646-439f-800a-909e36ecab80.png)
![boss_spell_collide 7](https://user-images.githubusercontent.com/102801485/180312051-bd48dfc5-5aa2-45d4-be16-9e27e1bbde8d.png)
![boss_spell_collide 8](https://user-images.githubusercontent.com/102801485/180312053-fd802e3a-dc08-4ccb-a8f3-89b05a486a0e.png)
![boss_spell_collide 9](https://user-images.githubusercontent.com/102801485/180312055-e8133080-bb74-4fee-94bf-68082bda2216.png)
![boss_spell_collide 10](https://user-images.githubusercontent.com/102801485/180312060-d1697069-8d6e-4da5-ab12-b72e7a44e0cd.png)
![boss_spell_collide 11](https://user-images.githubusercontent.com/102801485/180312062-dc6ad9f3-31b1-424b-91e7-51773cd6a125.png)
![boss_spell_collide 12](https://user-images.githubusercontent.com/102801485/180312063-1ca646a6-2a18-4232-a2b9-a279890bccc6.png)
![boss_spell_collide 13](https://user-images.githubusercontent.com/102801485/180312066-850981b8-2921-4fe6-8d40-c73df6b272a0.png)
![boss_spell_collide 14](https://user-images.githubusercontent.com/102801485/180312068-774aa1bf-ca54-4419-91d5-0e4128cb49d0.png)
![boss_spell_collide 15](https://user-images.githubusercontent.com/102801485/180312070-21ebf371-3991-45a0-977e-f2038e54407c.png)
![boss_spell_collide 16](https://user-images.githubusercontent.com/102801485/180312073-642a498f-bc65-479d-8465-014ff2cf8d4c.png)
![boss_spell_collide 17](https://user-images.githubusercontent.com/102801485/180312076-f2b1351d-1c91-4841-9db1-c94d629da661.png)
![boss_spell_collide 18](https://user-images.githubusercontent.com/102801485/180312079-882aa7e1-ca8b-422b-86a0-d4ee65128c6b.png)
![boss_spell_collide 19](https://user-images.githubusercontent.com/102801485/180312081-d38912a2-5020-4eba-9978-cc666285e43f.png)
![Uploading boss_spell_collide 20.png…]()

**Comment by alanos005** [comment]
![boss_spell_collide 1](https://user-images.githubusercontent.com/102801485/180312172-fb2d47e2-feda-462b-853a-8215dcd96ddb.png)
![boss_spell_collide 2](https://user-images.githubusercontent.com/102801485/180312173-296dbce5-862d-4d8c-a5b9-489cf042fe51.png)

sprite de colisão do projétil do boss
![boss_spell_collide 3](https://user-images.githubusercontent.com/102801485/180312175-a5c134cd-7714-44ad-97ea-5d81dbfa0194.png)
![boss_spell_collide 4](https://user-images.githubusercontent.com/102801485/180312179-53f73985-9f6e-4907-b4ec-ca4d5f059960.png)
![boss_spell_collide 5](https://user-images.githubusercontent.com/102801485/180312181-fa8cd302-9297-4276-aa4d-ad1910e9975f.png)
![boss_spell_collide 6](https://user-images.githubusercontent.com/102801485/180312182-2edf9957-383b-4821-b330-b54cdb19d33e.png)
![boss_spell_collide 7](https://user-images.githubusercontent.com/102801485/180312184-c9d65786-4523-4853-bbdc-9384b62ae272.png)
![boss_spell_collide 8](https://user-images.githubusercontent.com/102801485/180312186-7cb5e4ef-04cc-4398-991c-13c3b6740786.png)
![boss_spell_collide 9](https://user-images.githubusercontent.com/102801485/180312187-518983f4-132e-48fe-9210-5a9d7de98eb1.png)
![boss_spell_collide 10](https://user-images.githubusercontent.com/102801485/180312189-25e59be1-17f4-4c3c-a4e2-306f4821db0e.png)
![boss_spell_collide 11](https://user-images.githubusercontent.com/102801485/180312194-ce558ea2-d1ea-48bb-bd9a-9d0f9082ca44.png)
![boss_spell_collide 12](https://user-images.githubusercontent.com/102801485/180312196-753b233c-8ea8-459a-b689-e2a49a62c84e.png)
![boss_spell_collide 13](https://user-images.githubusercontent.com/102801485/180312201-5cd821ef-d583-4166-8d57-dbce6e1e7df0.png)
![boss_spell_collide 14](https://user-images.githubusercontent.com/102801485/180312203-136b6a03-d2e0-47a6-ac86-c1659a3d3d70.png)
![boss_spell_collide 15](https://user-images.githubusercontent.com/102801485/180312206-5507e70d-4918-43f4-9213-2cf9cb5c3ecd.png)
![boss_spell_collide 16](https://user-images.githubusercontent.com/102801485/180312211-36c3fe60-5e41-4c58-baff-ef92d9ed83f7.png)
![boss_spell_collide 17](https://user-images.githubusercontent.com/102801485/180312213-be5536f0-45b6-4d5c-900c-51824be91fc3.png)
![boss_spell_collide 18](https://user-images.githubusercontent.com/102801485/180312215-ada6520f-ddd1-41a6-9e9a-305f1cc5e28b.png)
![boss_spell_collide 19](https://user-images.githubusercontent.com/102801485/180312218-69a570b1-7df5-4985-a22f-c78a051790fc.png)
![boss_spell_collide 20](https://user-images.githubusercontent.com/102801485/180312220-e7af934a-cff1-4f9f-9325-355e899dd4d1.png)
![boss_spell_collide 21](https://user-images.githubusercontent.com/102801485/180312222-ad53db9f-5e2a-45b4-87c7-a0082c0b7d38.png)
![boss_spell_collide 22](https://user-images.githubusercontent.com/102801485/180312227-89b14645-9c1b-4fc3-a625-d0c33eed0ebc.png)

**Comment by pedrykolas** [comment]
![EYE_heIdles](https://user-images.githubusercontent.com/75922056/180315192-2ef281fe-1faf-4aa4-ba19-98174ceea3f7.png)
![PROJECTILE_blastLoop](https://user-images.githubusercontent.com/75922056/180315198-87a72a59-3c5b-4bc2-b2a2-0fb860dda76e.png)
![PROJECTILE_blastBurst](https://user-images.githubusercontent.com/75922056/180315203-ad3f8771-9352-4f30-b189-79f83809c689.png)
![EYE_electricDash](https://user-images.githubusercontent.com/75922056/180315211-66aec4fa-02fc-4c51-8cd2-f7ad67ecda5f.png)
![EYE_electricCharge](https://user-images.githubusercontent.com/75922056/180315218-1f67615b-8c43-4672-9880-df4b59f0d9d1.png)
![EYE_heDies](https://user-images.githubusercontent.com/75922056/180315222-5894b8fb-fb3d-4490-abe7-bb2615d10da6.png)
![EYE_heAwakens](https://user-images.githubusercontent.com/75922056/180315225-61cdb52f-15d5-4bf8-91ee-25f0a73a208c.png)
