### ISSUE TITLE
Rascunhos

### ISSUE THREAD

**Issue by pedrykolas** [El-Gato-Gordo/MageKnight#48]
![ironIcon (1)](https://user-images.githubusercontent.com/75922056/167511734-b9c21296-0ed6-4ce0-b6f1-481ac2eda605.png)

![image](https://user-images.githubusercontent.com/75922056/167623221-51956083-7cb1-4333-a3be-f4adc40e06dc.png)

![image](https://user-images.githubusercontent.com/75922056/167737955-5239f444-f5c3-4167-9fe1-eb82722c2390.png)
![image (1)](https://user-images.githubusercontent.com/104366549/168297295-cfa71db4-fb30-47ca-960f-665f036243a0.png)

**Comment by pedrykolas** [comment]
![image](https://user-images.githubusercontent.com/75922056/167272052-887bad6b-af74-47cf-afc8-1ef51af3221c.png)
![aaa](https://user-images.githubusercontent.com/75922056/167272070-b50f0dd1-3498-4a1e-b03a-c978465047aa.png)

**Comment by CaioBongs** [comment]
![image](https://user-images.githubusercontent.com/102802026/171869650-d30429ca-4c64-4962-b79b-272a38fa8e2d.png)
