### ISSUE TITLE
Escolha de Dificuldade

### ISSUE THREAD

**Issue by pedrykolasAlt** [El-Gato-Gordo/MageKnight#50]
Ícones para Dificuldade:
![image](https://user-images.githubusercontent.com/104366549/169659923-e9fdfdc8-5d52-4fc7-a3ab-654ba6543c27.png)

1: Normal (Jogo Base)
2: Difícil (Inimigos mais rápidos, agressivos e com mais saúde)
3: Brutal (Inimigos ainda mais rápidos, agressivos, além de se possível mais inimigos)

4: Infernal (Inimigos rápidos, agressivos e jogador sofre hitkill) [Liberado após terminar no modo Brutal]
5: Divino (Inimigos extremamente rápidos e agressivos, tanto o jogador quanto os inimigos sofrem hitkill; O jogador não pode ficar parado por mais de 5 segundos) [Liberado após terminar no modo Brutal]

**Comment by pedrykolas** [comment]
Botões para escolha de dificuldade
![image](https://user-images.githubusercontent.com/75922056/171514782-b0e9cf26-06ba-4bc9-949c-c10a36483869.png)

**Comment by pedrykolas** [comment]
![image](https://user-images.githubusercontent.com/75922056/171751352-b3a87b9f-14ce-4005-9427-0c11fe717c14.png)

**Comment by pedrykolasAlt** [comment]
Normal: ![image](https://user-images.githubusercontent.com/104366549/171955903-edbf7398-e53a-4098-ad2a-53db6322b250.png)

**Comment by CaioBongs** [comment]
FICO BONITAO MAIS N TEM!
