### ISSUE TITLE
Alterar Hitbox de acordo com frames

### ISSUE THREAD

**Issue by pedrykolas** [El-Gato-Gordo/MageKnight#55]
Fazer com que a hitbox do personagem seja alterada de acordo com os spritesheets, como os golpes do jogador.

Criei o golpe ao pressionar J (só dar um CTRL + F e pesquisar por keyJ)
Antes do código do golpe tem o do cooldown do golpe.

Linhas 109 - 125 são os códigos para adicionar os dois spritesheets dos golpes, criei um para esquerda e um para direita

**Comment by boidacarapreta** [comment]
Algo assim no final de `update()` ajuda?

```js
firstLevel.update = function () {

  [...]

  if (p_attacking) {
    player.setSize(128, 64);
  } else {
    player.setSize(64, 64);
  }
}
```

O personagem se desloca na tela, o que ainda não ficou bom...

**Comment by CaioBongs** [comment]
aaaAA
