### ISSUE TITLE
Integrar servidor de jogo e clientes

### ISSUE THREAD

**Issue by CaioBongs** [El-Gato-Gordo/MageKnight#60]
Modificar os clientes de https://github.com/boidacarapreta/adcipt20221/issues/23 e o servidor de https://github.com/boidacarapreta/adcipt20221/issues/29 e https://github.com/boidacarapreta/adcipt20221/issues/31 e integrá-los, de forma a ter um jogo multijogador em rede.

**Comment by boidacarapreta** [comment]
A tarefa não foi concluída: há erro na linha [linha 15 do arquivo index.html](https://github.com/El-Gato-Gordo/MageKnight/blob/main/client/index.html#L15). Com isso, o cliente não carrega o Socket.IO.
