### ISSUE TITLE
(Re) Conceito de Boss - Trio Parada Dura

### ISSUE THREAD

**Issue by CaioBongs** [El-Gato-Gordo/MageKnight#62]
A aparência do bichão será algo em referência a uma gárgula/ demônio/ dragão (something among [AMOGUS] those lines)

A luta utilizará 3 mecânicas do mago e a movimentação e ataque do cavaleiro, entre elas:

Mago: 
Tirinho que da dano (viish)
Parry que torna o inimigo vulnerável por um curto período de tempo
Pulo duplo (Um pulo que acontece duas vezes)

Cavaleiro:
Desviar, pular, atacar e se movimentar (entediante e sem inspiração feito as vestimentas do alan na primeira fase/ vai cagar caio)

Boss: primeira fase:
O Boss irá se movimentar no ar em alta velocidade e o mago terá que usar o seu (viish (pessimo nome)) para atacar o bichão, o desafio da fase vai ser desviar dos ataques do gárgulóide e tacar raiozinho ao mesmo tempo, (sendo o viish, a coordenação de ataque e movimento entre o cavaleiro e o mago as principais mecânicas dessa primeira fase)

[Rascunho do Pedrão (e do caiao)]

Boss: Primeira Fase:
- Boss fica acima, no ar, é um pouco maior que o cavaleiro;
- Principal ataque será o Vish do Mago, por conta do alcance;
- O boss, igual um beta male, fica jogando projéteis no Cavaleiro e Mago;
- Há chance do Gargulóide mandar de volta os projéteis do Mago; (talvez)
- Se movimentará em um padrão em alta velocidade, o projétil do mago será de baixa velocidade fazendo o desafio dessa fase desviar os projéteis e ao mesmo tempo acertar o boss

golpes: raiozinho rapido, giro soltando 3 feixes de raio e fazendo o uso do parry necessário

Boss: Segunda Fase:
- O boss fica blindão, bem maior do que antes; (provavelmente n)
- Agora o Boss utilizará golpes corpo a corpo, fazendo com que o parry e o pulo duplo sejam necessários para a vitória do mago e do cavaleiro
- Projetos do mago não surgirão mais efeito por conta de seus para-raios 

golpes: rolar no chao fazendo que o pulo duplo e parry sejam necessarios pra desviar desse golpe e investidas

**Comment by pedrykolasAlt** [comment]
![image](https://user-images.githubusercontent.com/104366549/172702812-450619d1-daaa-4175-beae-533b034ff506.png)

**Comment by pedrykolasAlt** [comment]
![image](https://user-images.githubusercontent.com/104366549/172703522-bb3e8e9e-0841-4cac-926b-8d3516d26bfb.png)

**Comment by CaioBongs** [comment]
vai ser uma ideia similar mas vai ser um zoiao

**Comment by alanos005** [comment]
![concept1_bossx](https://user-images.githubusercontent.com/102801485/179419732-d8c8e04a-1d6b-4855-857d-e2759e7a57c0.png)

**Comment by alanos005** [comment]
![BOSS_FASE1_SPRITE1](https://user-images.githubusercontent.com/102801485/179628845-840991f9-882a-4da0-a94b-fb930b9b9b8e.png)
![BOSS_FASE1_SPRITE2](https://user-images.githubusercontent.com/102801485/179628848-37614dc2-c91b-4743-a6b0-92773f092d82.png)
![BOSS_FASE1_SPRITE3](https://user-images.githubusercontent.com/102801485/179628850-4978ae31-be97-4de1-83ef-bdf8ab3ba077.png)
![BOSS_FASE1_SPRITE4](https://user-images.githubusercontent.com/102801485/179628851-e73ce798-9fe6-4f4a-aeaf-5402f01a3d61.png)
![BOSS_FASE1_SPRITE5](https://user-images.githubusercontent.com/102801485/179628852-92be25c9-7055-4231-847b-91468a70d12b.png)
![BOSS_FASE1_SPRITE6](https://user-images.githubusercontent.com/102801485/179628854-bc3ca0d8-4fd0-48f6-895e-58adfb816646.png)
![BOSS_FASE1_SPRITE7](https://user-images.githubusercontent.com/102801485/179628856-9097ecb4-9582-4b41-abca-16d51e1877d0.png)
![BOSS_FASE1_SPRITE8](https://user-images.githubusercontent.com/102801485/179628858-08c5f030-9499-44f7-bd97-6498ca3a927e.png)
![BOSS_FASE1_SPRITE9](https://user-images.githubusercontent.com/102801485/179628860-8cbf1483-00bb-45aa-ac86-af5748b2ea9f.png)
![BOSS_FASE1_SPRITE10](https://user-images.githubusercontent.com/102801485/179628862-43f86b1b-868b-45de-8130-ca5c04ff2ea7.png)
![BOSS_FASE1_SPRITE11](https://user-images.githubusercontent.com/102801485/179628863-5af2bedc-a946-4bfb-8ebb-beffd87efc98.png)
![BOSS_FASE1_SPRITE12](https://user-images.githubusercontent.com/102801485/179628866-13b42a04-cc6a-4504-92c9-d5f6d57498ba.png)
![BOSS_FASE1_SPRITE13](https://user-images.githubusercontent.com/102801485/179628867-699ef4c0-8b74-48f5-bd13-82d86bd02e08.png)
![BOSS_FASE1_SPRITE14](https://user-images.githubusercontent.com/102801485/179628868-4559e7b2-5ba2-4cf1-ba93-0a5b2d57fd0d.png)
![BOSS_FASE1_SPRITE15](https://user-images.githubusercontent.com/102801485/179628870-1abb41f5-f2c7-4bbf-a090-cdcd5473daba.png)
![BOSS_FASE1_SPRITE16](https://user-images.githubusercontent.com/102801485/179628871-de1476a9-4056-4054-988d-df6bee493430.png)
![BOSS_FASE1_SPRITE17](https://user-images.githubusercontent.com/102801485/179628872-53c262e2-34ca-4897-a504-8505b9e80168.png)
![BOSS_FASE1_SPRITE18](https://user-images.githubusercontent.com/102801485/179628875-7a5583b4-1432-4d50-a19a-852bd113d768.png)
![BOSS_FASE1_SPRITE19](https://user-images.githubusercontent.com/102801485/179628877-6bc240fb-0513-47e7-8e10-d1329b5c5549.png)
![BOSS_FASE1_SPRITE20](https://user-images.githubusercontent.com/102801485/179628879-d6b522ed-fb2c-4364-9ade-afd85d59138c.png)

**Comment by alanos005** [comment]
![BOSS_WAKENING_SPRITE1](https://user-images.githubusercontent.com/102801485/179629198-f2f19a61-294f-4ff2-9183-f9b70e25e2ef.png)
![BOSS_WAKENING_SPRITE2](https://user-images.githubusercontent.com/102801485/179629200-16ad1d22-73b4-42bf-aa47-e8bf49d4f8b5.png)

Animação Inicial
![BOSS_WAKENING_SPRITE3](https://user-images.githubusercontent.com/102801485/179629201-911507a5-32a3-4ebb-9c08-0b4fbb25f6bd.png)
![BOSS_WAKENING_SPRITE4](https://user-images.githubusercontent.com/102801485/179629204-a95c02e4-99c0-406d-beea-66fd3c8ef9de.png)
![BOSS_WAKENING_SPRITE5](https://user-images.githubusercontent.com/102801485/179629205-e1f47217-0011-42b2-a915-7a6123dba4d7.png)
![BOSS_WAKENING_SPRITE6](https://user-images.githubusercontent.com/102801485/179629207-8425f557-13b5-4114-b28d-2edbf00dd7fa.png)
![BOSS_WAKENING_SPRITE7](https://user-images.githubusercontent.com/102801485/179629208-932f5bee-bd0d-4482-be46-a80bf64541d1.png)
![BOSS_WAKENING_SPRITE8](https://user-images.githubusercontent.com/102801485/179629209-c3f2fc22-1448-4b0f-8e48-c88ad482e00c.png)
![BOSS_WAKENING_SPRITE9](https://user-images.githubusercontent.com/102801485/179629211-8df3f1f5-ac00-4ade-93e2-0a5a057694d5.png)
![BOSS_WAKENING_SPRITE10](https://user-images.githubusercontent.com/102801485/179629212-329be18a-d90c-41c3-a701-afb4ba959b58.png)
![BOSS_WAKENING_SPRITE11](https://user-images.githubusercontent.com/102801485/179629214-75fe7df9-965b-4536-90e9-79ce2bf2644d.png)
![BOSS_WAKENING_SPRITE12](https://user-images.githubusercontent.com/102801485/179629215-3118c7b7-b002-4346-921a-07706b7a60e1.png)
![BOSS_WAKENING_SPRITE13](https://user-images.githubusercontent.com/102801485/179629219-9b379dd9-9820-42ae-ba5c-d117a68b08f6.png)
![BOSS_WAKENING_SPRITE14](https://user-images.githubusercontent.com/102801485/179629223-1fc006db-688b-420b-bb94-06b6c16aba32.png)
![BOSS_WAKENING_SPRITE15](https://user-images.githubusercontent.com/102801485/179629224-f9ffcabe-6d47-4880-ad44-326ea208e9a8.png)
![BOSS_WAKENING_SPRITE16](https://user-images.githubusercontent.com/102801485/179629226-64b46356-345b-412f-ba76-75c3b29dede3.png)
![BOSS_WAKENING_SPRITE17](https://user-images.githubusercontent.com/102801485/179629228-9874a851-cdb6-4f54-a1a7-219ca710438c.png)
![BOSS_WAKENING_SPRITE18](https://user-images.githubusercontent.com/102801485/179629231-4e259037-738e-4a38-b782-1682c3e86533.png)
![BOSS_WAKENING_SPRITE19](https://user-images.githubusercontent.com/102801485/179629232-3949f163-d8be-4b0a-8a77-2135beb7771a.png)
![BOSS_WAKENING_SPRITE20](https://user-images.githubusercontent.com/102801485/179629235-35bc34fb-92bd-4419-8fb2-7d61f835f04d.png)

**Comment by alanos005** [comment]
![BOSS_ATTACKING_FASE1](https://user-images.githubusercontent.com/102801485/179629850-e00a40f7-3aca-44eb-9181-e6aadbc58beb.png)
![BOSS_ATTACKING_FASE2](https://user-images.githubusercontent.com/102801485/179629851-af9a5eac-8612-49aa-8a0a-fe976a1ff067.png)
![BOSS_ATTACKING_FASE10](https://user-images.githubusercontent.com/102801485/179629868-e62d5c35-9b45-42f7-984b-42221d711010.png)
![BOSS_ATTACKING_FASE11](https://user-images.githubusercontent.com/102801485/179629870-630f6da6-6a7a-4405-ae71-9e52f113f7a3.png)
![BOSS_ATTACKING_FASE7](https://user-images.githubusercontent.com/102801485/179629862-46ade65f-4e32-401d-b453-87fe1ea6e76f.png)
![BOSS_ATTACKING_FASE8](https://user-images.githubusercontent.com/102801485/179629864-6b6014f8-a3bf-4b05-8dac-5aeddce53902.png)
![BOSS_ATTACKING_FASE9](https://user-images.githubusercontent.com/102801485/179629865-ec13e90f-e5fc-460a-8567-e3bb7a6bf936.png)
![BOSS_ATTACKING_FASE3](https://user-images.githubusercontent.com/102801485/179629853-827e0c92-5160-4992-94f9-4552e5b1c8ea.png)
![BOSS_ATTACKING_FASE4](https://user-images.githubusercontent.com/102801485/179629855-f3a00bf9-8e23-4a5d-9d57-91e12074ca6b.png)
![BOSS_ATTACKING_FASE5](https://user-images.githubusercontent.com/102801485/179629857-98029058-02d8-4def-b298-8b6285d3cfc0.png)
![BOSS_ATTACKING_FASE6](https://user-images.githubusercontent.com/102801485/179629859-80745e37-cd69-44de-ada7-4d2071c070ce.png)

Animação de ataque (FASE1)

**Comment by alanos005** [comment]
![BOSS_ATTACKING_FASE1](https://user-images.githubusercontent.com/102801485/179630037-99e5cc90-02b4-4d3a-b2b5-789237d54697.png)
![BOSS_ATTACKING_FASE2](https://user-images.githubusercontent.com/102801485/179630041-d3fc0a47-e64f-43e0-9f0f-9b5c4ff78883.png)
![BOSS_ATTACKING_FASE3](https://user-images.githubusercontent.com/102801485/179630044-b1b6ccb0-9ef9-4329-a9b3-29159a6f89ab.png)
![BOSS_ATTACKING_FASE4](https://user-images.githubusercontent.com/102801485/179630045-5c077880-be94-4961-ac37-256a1aab8cbd.png)
![BOSS_ATTACKING_FASE5](https://user-images.githubusercontent.com/102801485/179630046-6a8d694c-0181-47ba-809a-0d4b62639dea.png)
![BOSS_ATTACKING_FASE6](https://user-images.githubusercontent.com/102801485/179630048-3a274902-818d-446b-9ff1-67c1fa62fc42.png)
![BOSS_ATTACKING_FASE7](https://user-images.githubusercontent.com/102801485/179630049-689960e5-6c00-4c9d-88bf-c348ed5b23c5.png)
![BOSS_ATTACKING_FASE8](https://user-images.githubusercontent.com/102801485/179630050-a33776c7-b0aa-44c8-9aff-8075c1b8f49a.png)
![BOSS_ATTACKING_FASE9](https://user-images.githubusercontent.com/102801485/179630052-9871e074-300c-4dad-87ae-90a4e6ed8b05.png)
![BOSS_ATTACKING_FASE10](https://user-images.githubusercontent.com/102801485/179630054-4c2bbd9a-8d85-4992-8fae-7c2046534fc5.png)
![BOSS_ATTACKING_FASE11](https://user-images.githubusercontent.com/102801485/179630055-722e78b3-71c5-48f0-bbbc-2e2a4e3bb1cb.png)

Animação de Ataque (FASE 1)

**Comment by alanos005** [comment]
![BOSS_FASE2_CHARGING1](https://user-images.githubusercontent.com/102801485/179644800-1f7f6e5d-8281-4cf4-9765-5eb9ba693272.png)
![BOSS_FASE2_CHARGING2](https://user-images.githubusercontent.com/102801485/179644801-e0bee0df-effe-42d6-a4af-22ef99bdbe58.png)
![BOSS_FASE2_CHARGING3](https://user-images.githubusercontent.com/102801485/179644807-e73c38c8-71f5-45ae-80d4-26e414c225f2.png)
![BOSS_FASE2_CHARGING4](https://user-images.githubusercontent.com/102801485/179644811-920c7d66-4a31-4590-8d2d-a305a4cb8843.png)
![BOSS_FASE2_CHARGING5](https://user-images.githubusercontent.com/102801485/179644813-07feb004-02de-4bee-b21a-2cc8901f72ec.png)
![BOSS_FASE2_CHARGING6](https://user-images.githubusercontent.com/102801485/179644814-198a4547-3aab-4eda-9a93-c2dc3ce7a2f5.png)
![BOSS_FASE2_CHARGING7](https://user-images.githubusercontent.com/102801485/179644815-8348ed4c-1150-4c3f-8295-75f5be4c5596.png)
![BOSS_FASE2_CHARGING8](https://user-images.githubusercontent.com/102801485/179644817-6628474d-84b9-4ae8-b9be-4833bad21e12.png)
![BOSS_FASE2_CHARGING9](https://user-images.githubusercontent.com/102801485/179644818-a9b9a900-fc71-43ff-bd20-34b8e418ba97.png)
![BOSS_FASE2_CHARGING10](https://user-images.githubusercontent.com/102801485/179644821-3a1b8c61-44b6-4319-b31a-ff36b650152f.png)
![BOSS_FASE2_CHARGING11](https://user-images.githubusercontent.com/102801485/179644822-58e4a139-826f-46c5-b49a-fb54865ce031.png)
![BOSS_FASE2_CHARGING12](https://user-images.githubusercontent.com/102801485/179644823-12b7171c-d9b0-4d3c-b320-d0096f57ba1e.png)
![BOSS_FASE2_CHARGING13](https://user-images.githubusercontent.com/102801485/179644826-1b1bd13b-e7ed-4d5f-aa23-c119e0685a88.png)
![BOSS_FASE2_CHARGING14](https://user-images.githubusercontent.com/102801485/179644827-50cc38df-8bfe-4d19-a6d1-ad236aa772c7.png)
![BOSS_FASE2_CHARGING15](https://user-images.githubusercontent.com/102801485/179644829-70a58801-6839-484e-bc52-519bea9ee2b7.png)
![BOSS_FASE2_CHARGING16](https://user-images.githubusercontent.com/102801485/179644831-6e07dc38-7207-486e-8d3b-bb210a46e9ca.png)
![BOSS_FASE2_CHARGING17](https://user-images.githubusercontent.com/102801485/179644832-2d7b0282-7422-4613-bb6c-f35d0a45807f.png)
![BOSS_FASE2_CHARGING18](https://user-images.githubusercontent.com/102801485/179644833-2ccc507d-0a8a-4790-a37c-fe4d4c4da04e.png)
![BOSS_FASE2_CHARGING19](https://user-images.githubusercontent.com/102801485/179644836-04d5bc15-f584-4a5a-9e23-d945b7ca3faf.png)

Animação de Transição (FASE 1 > FASE 2)

**Comment by alanos005** [comment]
![SPELL_MAGE_TESTE](https://user-images.githubusercontent.com/102801485/179646309-942f18c7-40ce-49ad-b4eb-09ec69614880.png)
sprite de projétil pro pedro programar e deixa pronto tudo (tanto pro boss quanto pro mago) (leitinho mandou lembranças)

**Comment by alanos005** [comment]
![MAGE_SPELL_1](https://user-images.githubusercontent.com/102801485/179769337-33fe70b9-9de6-48ea-bdd1-c78de41eadce.png)
![MAGE_SPELL_2](https://user-images.githubusercontent.com/102801485/179769343-5bcd151f-f7c9-4a11-85bd-caa3c95b4b83.png)
![MAGE_SPELL_3](https://user-images.githubusercontent.com/102801485/179769346-90262143-8049-4d42-ae8e-f70ca08ff938.png)
![MAGE_SPELL_4](https://user-images.githubusercontent.com/102801485/179769350-63953d0c-e572-438e-bf0f-aba95893e4a1.png)

**Comment by alanos005** [comment]
![spell_collide 1](https://user-images.githubusercontent.com/102801485/180030131-fd3f4aa7-0953-4985-bffe-f99dbad52119.png)
![spell_collide 2](https://user-images.githubusercontent.com/102801485/180030134-5f6cfcb0-9574-43b1-aa62-9d593aac42e5.png)
![spell_collide 3](https://user-images.githubusercontent.com/102801485/180030139-83eeb5ae-a242-4db8-8d2c-654c8fa604bc.png)
![spell_collide 4](https://user-images.githubusercontent.com/102801485/180030140-c4b141b5-4d49-4167-b8d2-8128ddb067e6.png)
![spell_collide 5](https://user-images.githubusercontent.com/102801485/180030142-096772e2-6db6-4d89-b697-bedbe44f43b0.png)

Sprites de colisão do projétil do mago
