### ISSUE TITLE
Mostrar pro Pessoal

### ISSUE THREAD

**Issue by pedrykolas** [El-Gato-Gordo/MageKnight#77]
Sprites:

![iudle](https://user-images.githubusercontent.com/75922056/180448165-fa38cf25-b9b3-4785-b3d0-a22f100f02c0.gif)

![walk](https://user-images.githubusercontent.com/75922056/180447999-5d442e7f-5317-4bfb-8dea-2e5ff6d886ea.gif)

![fall rise](https://user-images.githubusercontent.com/75922056/180447884-72195a5f-fd90-40c3-82cf-3ee7921f24b3.gif)

![image](https://user-images.githubusercontent.com/75922056/180447728-5c9990e3-04e5-4376-84cf-6794a2fab1e5.gif)

**Comment by CaioBongs** [comment]
![image](https://user-images.githubusercontent.com/102802026/179358749-ecdf4c32-1acd-47f8-a4f7-a7431a67f800.png)
![image](https://user-images.githubusercontent.com/102802026/179358759-fd204959-2dc9-410d-95b1-211c119663b7.png)
![image](https://user-images.githubusercontent.com/102802026/179358765-b2a47175-f8f1-44fe-b9bd-0ea6f47e9384.png)
![image (3)](https://user-images.githubusercontent.com/102802026/179426396-0318180f-1355-459c-9371-4b346bdc3b62.png)

**Comment by alanos005** [comment]
![BOSS_FASE2_CHARGING1](https://user-images.githubusercontent.com/102801485/180448912-07794852-28ac-47e6-8413-76e6075fd380.gif)
![BOSS_WAKENING_SPRITE1 (1)](https://user-images.githubusercontent.com/102801485/180448916-a248c93d-b93a-4aa1-b429-fdeff417706b.gif)
![BOSS_WAKENING_SPRITE1](https://user-images.githubusercontent.com/102801485/180448917-cef927bd-c972-405b-88f9-51fc2621f1ce.gif)
![BOSS_SPELL_1](https://user-images.githubusercontent.com/102801485/180448923-6a1c6796-3a4f-4257-b96f-077471a84c97.gif)
![boss_comlaser1](https://user-images.githubusercontent.com/102801485/180448926-80b660b3-8563-41ae-affc-54cd090556a2.gif)
![kenkidama1](https://user-images.githubusercontent.com/102801485/180448930-83a3b62f-9515-4822-a854-58a893427571.gif)
![boss_spell_collide 1](https://user-images.githubusercontent.com/102801485/180448932-b2c75e49-ab4c-4a48-9ae1-6723f3bdbc69.gif)
![mage_spell_horizontal_right1](https://user-images.githubusercontent.com/102801485/180448934-883236b9-ebc0-4a79-a89a-8c9676b1b3e7.gif)
![mage_spell_collide1](https://user-images.githubusercontent.com/102801485/180448938-928b0821-ff50-4f16-8987-5f9695414a94.gif)

**Comment by CaioBongs** [comment]
_**MOVIMENTAÇÃO BASE:**_

**IDLE:**
Tamanho de cada Frame: 150x150 [Feito em 75x75]

[Resultado]
![image (4)](https://user-images.githubusercontent.com/104366549/172948922-37a27651-287a-4f44-a329-959a63dba724.gif)

[Aumentado]
![image (2) (1)](https://user-images.githubusercontent.com/104366549/172951260-203b26da-430d-4234-bcad-95acc900b1da.png)

![image (2) (3)](https://user-images.githubusercontent.com/104366549/172951317-c76bcfb4-d647-47cd-8653-8adf798274c0.png)

[Original]
![image (2)](https://user-images.githubusercontent.com/104366549/172951250-857fcc2d-5020-4a76-a087-3b1ded136d3f.png)

![image (2) (2)](https://user-images.githubusercontent.com/104366549/172951293-ba3fb404-9620-410a-b9d7-e45e62de463f.png)

**WALK:**
Tamanho de cada Frame: 150x150 [Feito em 75x75]

[Resultado]
![image](https://user-images.githubusercontent.com/104366549/172955259-e546deaf-c589-4257-a674-edaee6b0cdfa.gif)


[Aumentado]
![image (7)](https://user-images.githubusercontent.com/104366549/172910745-397683da-c773-4cb9-b811-36cc282cab7c.png)

![image (9)](https://user-images.githubusercontent.com/104366549/172910802-7c72951b-2c0a-4057-a7e1-612fe80458ce.png)


[Original]
![image (6)](https://user-images.githubusercontent.com/104366549/172910751-d6d22b72-9f63-4094-8269-0528a36eeb77.png)

![image (8)](https://user-images.githubusercontent.com/104366549/172910796-0a5fc7a9-fecb-4c37-b3a4-33fb88dc3562.png)

**RUN:**

![image](https://user-images.githubusercontent.com/75922056/176661618-692416b0-7722-438f-81db-7a67694acc55.png)
![image (1)](https://user-images.githubusercontent.com/75922056/176661631-4c917930-fb59-4a59-9616-1787fe169cb6.png)



**RISING AND FALLING:**
Tamanho de cada Frame: 150x150 [Feito em 75x75]

[Resultado]
![image](https://user-images.githubusercontent.com/104366549/172957944-120b779c-203b-4c27-8676-79af35fe5637.gif)


[Aumentado]
![bigRiseRight](https://user-images.githubusercontent.com/104366549/172956920-100e1ca5-cda3-4d01-96b6-14052437f6bd.png)

![bigRiseLeft](https://user-images.githubusercontent.com/104366549/172956919-5fe4d795-804a-4c6f-86d5-03d72649e44e.png)


![bigFallRight](https://user-images.githubusercontent.com/104366549/172956991-c01ecdc0-9925-4d8f-a663-10328127d8e8.png)

![bigFallLeft](https://user-images.githubusercontent.com/104366549/172956996-2f801810-7f43-4824-819b-180f53db2af6.png)

[Original]
![smallRiseRight](https://user-images.githubusercontent.com/104366549/172956962-76f4206b-8d5e-44d8-8d70-0062b3559d7e.png)

![smallRiseLeft](https://user-images.githubusercontent.com/104366549/172956967-c6041bdb-3c6a-48d0-90df-1908da984f8c.png)


![smallFallRight](https://user-images.githubusercontent.com/104366549/172957014-5529d6ac-42b8-4542-86f7-9ebf7a63a7cf.png)

![smallFallLeft](https://user-images.githubusercontent.com/104366549/172957023-1290c6ad-8ca7-40ac-8555-8af7b27ae892.png)

**ATTACKING**
![image (1)](https://user-images.githubusercontent.com/75922056/178167273-fa6f7c1b-8380-4a16-9d87-0891b7175f15.png)

![image](https://user-images.githubusercontent.com/75922056/178167271-e2e0fbaa-ac8c-41f3-a9f8-b0f53b3d7555.png)

[Andar E Pular]

![sprite1_knightready1](https://user-images.githubusercontent.com/102801485/172266377-299b4ca9-698e-4cfb-b832-06f908124a58.png)
ataques loco de teste pq o alan demora mt pra fazer os sprite

@alanos005 @alanos005 @alanos005 

![MK-sideatkRight](https://user-images.githubusercontent.com/75922056/177221190-27917d4a-8229-4a37-adfd-a3760e07d161.png)
![MK-sideatkLeft](https://user-images.githubusercontent.com/75922056/177221185-ef098c58-cadb-4e43-9c77-533596b8b8c7.png)

**Comment by CaioBongs** [comment]
[Trilha Sonora.zip](https://github.com/El-Gato-Gordo/MageKnight/files/9162073/Trilha.Sonora.zip)

Músicas feitas utilizando BeepBox (beepbox.co)

Sons cavaleiro
[AudioCavaleiro.zip](https://github.com/El-Gato-Gordo/MageKnight/files/9126060/AudioCavaleiro.zip)


Sons mago
[AudioMago.zip](https://github.com/El-Gato-Gordo/MageKnight/files/9126713/AudioMago.zip)


Sons inimigo
[AudiosBoss.zip](https://github.com/El-Gato-Gordo/MageKnight/files/9126059/AudiosBoss.zip)

Notas: Sons de vozes do boss e do cavaleiro foram feitos e editados por mim, quanto aos demais sons foram pegos de uns sources gratuitos mas foram editados também (utilizando o Vegas), foram utilizados sons de vidro, fogo, uma motoserra e grunhidos que me garantirão longas férias na Colônia Santana.

**Comment by pedrykolas** [comment]
https://user-images.githubusercontent.com/75922056/180449994-c212228d-2a1c-4894-8c69-0ac30cb1b7e8.mp4

**Comment by alanos005** [comment]
![166918720-aa150a6a-165f-49c3-9296-0a031248a8c3](https://user-images.githubusercontent.com/102801485/180452394-e683bbdb-1aa8-4e35-9d75-4a6a4e83e5a6.png)
![ataque_cavaleiro_aereo](https://user-images.githubusercontent.com/102801485/180452417-29c45495-c9ee-40fa-8a4b-03c49972103e.png)
![ataque1](https://user-images.githubusercontent.com/102801485/180452420-578c6510-6716-475f-bd65-7b1940e9533c.png)
![logo](https://user-images.githubusercontent.com/102801485/180452425-9e1594ae-a37c-4329-a693-84c74053c4fb.png)

**Comment by alanos005** [comment]
![fundo](https://user-images.githubusercontent.com/102801485/180668568-f5c0b637-0b62-4801-87d1-b5b382d3804b.png)
