### ISSUE TITLE
Botão dos Mobile

### ISSUE THREAD

**Issue by pedrykolasAlt** [El-Gato-Gordo/MageKnight#79]
![BUTTON_SQUAREM](https://user-images.githubusercontent.com/104366549/180630708-4a926984-44eb-44d1-af04-c22e05dd48a9.png)
![BUTTON_CIRCLEM](https://user-images.githubusercontent.com/104366549/180630717-8ada88f1-c946-491b-aa63-2487c65509ed.png)
![BUTTON_UPM](https://user-images.githubusercontent.com/104366549/180630709-bf40398c-5b5b-438e-ab07-889ea83e8f63.png)
![BUTTON_RIGHTM](https://user-images.githubusercontent.com/104366549/180630710-eb29a074-d845-41f4-98b3-0eb92cf62542.png)
![BUTTON_LEFTM](https://user-images.githubusercontent.com/104366549/180630711-b2dda419-4ed5-4852-ac4a-fa76634b5c80.png)
![BUTTON_CIRCLEK](https://user-images.githubusercontent.com/104366549/180630712-43ece8f0-c31d-43aa-b732-9016ccc9d32e.png)
![BUTTON_UPK](https://user-images.githubusercontent.com/104366549/180630713-497df32b-5e0c-46b4-bf88-e9d5dc2606b2.png)
![BUTTON_RIGHTK](https://user-images.githubusercontent.com/104366549/180630714-6c5bcfd7-1117-43ec-89f1-01d193a5d8a7.png)
![BUTTON_LEFTK](https://user-images.githubusercontent.com/104366549/180630715-3fc3c0c7-6e15-448d-a7fc-76aa051161b8.png)
![BUTTON_SQUAREK](https://user-images.githubusercontent.com/104366549/180630716-5400d4e6-e3ac-454d-a65d-72e31c639b8b.png)

**Comment by alanos005** [comment]
![seta1](https://user-images.githubusercontent.com/102801485/180630979-88b4cd68-4a84-4f39-a226-f473b0f6b74c.png)
![seta2](https://user-images.githubusercontent.com/102801485/180630981-50b117cc-6bba-48d2-8719-3f4ceac47bea.png)
![seta3](https://user-images.githubusercontent.com/102801485/180630982-701baa55-c51d-48a1-8d09-5a0a104e3ab4.png)
![seta4](https://user-images.githubusercontent.com/102801485/180630983-7b94a260-b29a-4c51-b64b-33f84bfe40ae.png)
![seta5](https://user-images.githubusercontent.com/102801485/180630984-ac271184-70a8-4c7e-8499-1da1315f50e5.png)
![seta6](https://user-images.githubusercontent.com/102801485/180630985-fdc0a278-60ae-47be-920e-c06569fa7c1d.png)
![seta7](https://user-images.githubusercontent.com/102801485/180630986-d023e229-7494-430e-8987-6a2b4f1f6a0b.png)
![seta8](https://user-images.githubusercontent.com/102801485/180630987-c491e86a-ac7c-46bc-acb9-2a8520c1c019.png)
