### ISSUE TITLE
Gameplay/Mecânicas/História

### ISSUE THREAD

**Issue by pedrykolas** [El-Gato-Gordo/MageKnight#8]
ESBOÇO!

**Nome do Jogo?**

Um jogo 2D sobre um cavaleiro cego e um mago que não pode mais andar, ambos que após se conhecerem partem em busca de um artefato que poderia trazer de volta a visão do cavaleiro, e o movimento das pernas do mago.

O jogo foca na forma como o cavaleiro e o mago complementam as carências um do outro por meio das habilidades únicas de cada um e a comunicação entre os dois jogadores, um com os controles do cavaleiro, e outro com o mago.

**Ideias básicas do jogo:**

- HP e MANA
- O jogo é 2D, com estilo pixelizado;
- O cavaleiro e o mago são o mesmo personagem no jogo;
- Um jogador controla as ações do cavaleiro e outro do mago;

- **Ações básicas do cavaleiro:**
 1. Andar para esquerda e direita;
 2. Saltar;
 3. Ataques corpo-a-corpo;
 4. Aparar golpes.
 
- **Ações básicas do mago:**
 1. Evasão mágica;
 2. Salto duplo;
 3. Ataques à longa-distância;
 4. Criação de plataformas.

- **Ao longo do jogo, tanto o cavaleiro quanto o mago liberam outras habilidades como:**
 1. Cavaleiro: Golpe forte, investida, arremessar o Mago para alcançar outros locais, etc.;
 2. Mago: Magias mais poderosas, planar, cura, etc.

- **A história pode ser simples e talvez até clichê, primeiramente vejo:**
 1. O mago e o cavaleiro acabam se encontrando numa floresta, ambos perdidos pois o cavaleiro está cego, e o mago não pode sair dali por conta de suas pernas;
 2. A partir daí, ambos têm um breve diálogo e o jogo se inicia com um tutorial simples;
 3. Quando ambos saem da floresta, recebem a informação que há um artefato que pode recuperar a visão do cavaleiro, e a mobilidade das pernas do mago, e então este se torna o objetivo de ambos;
 4. No fim, o boss final também é uma dupla, ambos mais frágeis e fracos que o cavaleiro e o mago juntos, é um boss final fácil. sendo então:
 4.1. Uma opção finalizar o boss, e então permitir que os dois personagens se recuperem;
 4.2. Ou então, o jogador deve sobreviver desviando e aparando os golpes do chefe até o ponto de ser possível perceber que o cavaleiro e o mago mudaram de ideia, uma vez que há alguém que precise mais do artefato do que eles, ainda mais que conseguiram chegar daquela forma até o ponto que estão;
 4.3. O dilema só ocorre porque o artefato é limitado.
 5. O jogo tem dois finais.
 
- **Inimigos Menores:**
 1. Cavaleiros
 2. Magos
 3. Arqueiros/Besteiros
 4. Infantaria
 5. Ogros/Trolls
 6. Lobos
 7. Duendes/Goblins
 8. Estatuas Vivas
 9. Quimeras
 10. Morcegos/Duendes Voadores
 11. Dracos/Wyverns
 12. Bichos Estranhos tipo:
 12.1. Canhão Ambulante
 12.2. Árvore Hostil
 12.3. Poltergeists (espadas, vasos e outros objetos voadores)
 13. Espíritos
 13.1. De fogo [Se jogam e põe o Cavaleiro e o Mago em chamas]
 13.2. De gelo [Se jogam e congelam o Cavaleiro e o Mago]
 13.3. Do trovão [Se jogam, causando dano e paralisando momentaneamente o Cavaleiro e o Mago]

- **Chefes:**
1. Cavaleiro Maromba num Cavalo Maromba
2. Mago Absurdo
3. Louco
4. Dragão Insano
4.1. Fica numa montanha, o Cavaleiro e o Mago precisão escalar enquanto evitam os sopros de fogo do Dragão [Se escondendo atrás de pedras e evitando também espíritos de fogo por exemplo];
4.2. Quando chegam no topo, ambos devem lutar contra o dragão
5. Sicário sem Braço [Vampirão!!]
6. Dragão Insano de Gelo
6.1. Fica numa montanha também, porém o Cavaleiro e o Mago devem seguir uma trilha perto de penhascos enquanto evitam Ventos gélidos;
6.2. Para ser mais difícil que o primeiro Dragão, este além de possuir mais ataques, invoca espíritos de gelo e seu sopro, claramente, congela quem for atingido.
7. Cavaleiro Dourado
8. Díade Fraternal 

- **Efeitos:**
1. Em chamas [Cavaleiro fica incapaz de atacar e sofre dano com o tempo, precisa apertar repetidamente um botão para apagar o fogo ou então o Mago acelera o processo usando mana]
2. Congelado [Cavaleiro e Mago ficam congelados, o mago pode derreter o gelo rapidamente usando mana, ou então o cavaleiro pode tentar quebrar o gelo apertando repetidamente um botão]
3. Amarrado por vinhas/cordas/correntes [Cavaleiro fica incapaz de mover e o Mago não pode ajudar o Cavaleiro à desviar, dessa forma o Cavaleiro deve cortar/romper as vinhas/cordas/correntes com sua espada]
4. Sonolento [Impede o Mago de usar magia e o Cavaleiro fica mais lento, é necessário usar um botão alguma vezes para que o Cavaleiro acorde o Mago]
5. Envenenado [Após ser envenenado, o Cavaleiro começa à levar pouco dano com o tempo, porém a única forma de curar é com um feitiço do Mago]
6. Irritado [Cavaleiro perde a capacidade de aparar e passa à receber o dobro de dano, após desviar de golpes com ajuda do Mago, fica lento por um curto período]

- **Armadilhas/Adversidades:**
1. Armadilhas de Urso [Causam dano e prendem o Cavaleiro, necessita de um golpe para se livrar]
2. Minas Mágicas
2.1. Explosivas [Causam dano e arremessam o Cavaleiro e o Mago para longe, o Mago é derrubado do Cavaleiro]
2.2. Soporíficas [Criam uma grande nuvem soporífica]
2.3. De Napalm [Causam dano direto e põem fogo no Cavaleiro e no Mago]
2.4. De Raízes/Correntes [Prendem o cavaleiro com raízes/correntes e causam dano enquanto estiver preso]
3. Água [Cavaleiro é mais lento para se mover, não pode pular e evasão é menos eficaz; Se estiver submerso, após um curto período passa à receber dano; Pode ser congelada pelo Mago ou Inimigos; Cavaleiro é congelado e recebe dano com o tempo se estiver submerso em água congelada]
4. Ventos
4.1. Ventos Comuns [Empurram o Cavaleiro e o Mago para os lados]
4.2. Ventos Gélidos [Empurram o Cavaleiro e o Mago para os lados, além de congelá-los se ficarem muito tempo expostos]

-**Itens**
1. Consumíveis:
1.1. Comida [Permite recuperar HP]
1.2. Suco de Tomate Azul [Permite recuperar mana; Outra forma de recuperar mana é acertar 3 golpes físicos seguidos]
1.3. Brasa Serena [Dá imunidade ao frio por 3 minutos]
1.4. Inércia Glacial [Dá imunidade ao calor por 3 minutos]
2. Equipáveis do Cavaleiro:
2.1. Runa do Espelho [Aparos com sucesso permitem um golpe poderoso]
2.2. Presa de Morcego [Cada 5 golpes seguidos permitem recuperar 1 HP, com espera de 30 segundos entre cada cura]
2.3. Talismã do Inconsequente [Ficar irritado agora faz com que o Cavaleiro recebe 3x mais dano, porém seus ataques se tornam mais poderosos quando irritado; Ficar irritado se torna mais e dura mais]
3. Equipáveis do Mago:
3.1. Anel de Solaris [Estende a duração das chamas nos inimigos e aprimora o dano causado]
3.2. Piercing do Sicário sem Braço [Aumenta o poder de feitiços quando o HP for baixo]
3.3. Monóculo Espelhado da Catedral Cerúlea [Dá +5 de mana máxima em troca de visão reduzida]
4. Talentos de Sinergia:
4.1. Aço Atroz [Ataques fortes do Cavaleiro são imbuídos em chamas, com chance maior de botar fogo; E os feitiços de fogo do mago são imbuídos com aço, causando mais dano físico com menos chance de botar fogo]
4.2. Vitalidade Etérea [HP e mana se tornam um só, desta forma feitiços são conjurados sacrificando vitalidade, porém tanto estes feitiços quanto golpes comuns se tornam mais poderosos]
4.3. Metal Gélido [Ataques fortes do cavaleiro são imbuídos com ventos congelantes, com chance de congelar inimigos; E os feitiços glaciais do mago são imbuídos com aço pesado, demoram mais para serem conjurados mas causam mais dano]

- **Interações**
1. Pontos de Controle;
1.1. Fogueiras
1.2. Servem para salvar o jogo e reabastecer comida e suco de tomate azul
1.3. Recuperam HP e MANA

**Comment by CaioBongs** [comment]
tbm n tem!
